### PR TITLE
Moved navbar from layout to separate component

### PR DESCRIPTION
**Pull request by BerniWittmann**
I sourced the navbar out to a navigation component to prevent duplicate code when having multiple layouts that all require the navbar.

### CODE REVIEW

**Comment by petervmeijgaard** [comment]
I don't agree with this decision. The navbar is bloated with business logic, like the name of the application and the pages. I like to keep the components as dumb as possible.
Only the layout files and page files should have some sort of business logic.

**Comment by BerniWittmann** [comment]
I get your point and I think this is a good way to go. 
But wouldn't it still be good to move the navbar to a separate file (not as a component but maybe to `utils` folder)
My business case will include having multiple layouts that all should contain the navbar. Having it not separated would cause a lot of duplicate code and if I want to update the nav I would have to do it in every layout. 

I understand that you want to keep your components dumb, but i still think it may be a good idea to somehow separate the nav from the layout. 
But you're the maintainer and you're doing great work so feel free to close this, if you want

**Comment by petervmeijgaard** [comment]
Thanks for your quick reply. I agree that separating the navbar would be ideal, but I don't think this is the right solution. Unfortunately, Bootstrap is designed in such a way that makes it fairly difficult to use and create standalone components. If you're structuring your components in a more BEM-oriented way, you can avoid this problem.
For instance, in my [scam-alert](https://github.com/petervmeijgaard/scam-alert) repo, I'm using a BEM oriented approach. The components are dumbed down and only receive data from props and slots.
An example is the [navigation-component](https://github.com/petervmeijgaard/scam-alert/blob/master/resources/frontend/src/components/navigation/navigation.vue).
This way you could create a navigation using the following syntax from the [base-layout](https://github.com/petervmeijgaard/scam-alert/blob/master/resources/frontend/src/layouts/base/base.vue):
``` Vue
<template>
  <v-navigation>
    <v-navigation-item>
      <v-navigation-link :route="{ name: 'home.index' }">
        <v-navigation-content>
          Home
        </v-navigation-content>
      </v-navigation-link>
      <v-navigation-link :route="{ name: 'scammers.index' }">
        <v-navigation-content>
          Scammers
        </v-navigation-content>
      </v-navigation-link>
    </v-navigation-item>
  </v-navigation>
</template>
<script>
  export default {
    //
  };
</script>
```

For a while, I've been thinking about removing Bootstrap and jQuery and create my own custom components. These standalone components will be structured using BEM and should fix your problem. The problem is that I don't want to add too much bloat to my project.
For the meantime, you could choose to put a navbar with business logic in some sort of a `shared` directory.

Feel free to share your opinion 😄

**Comment by BerniWittmann** [comment]
@petervmeijgaard You're right, that this approach would be good, but out of scope for this. 
Instead of writing your own UI components, you could take a look at [Element](http://element.eleme.io/#/en-US). It's the same direction as you proposed and feels like Bootstrap for Vue 😉 

I think for me right now it, it's enough to fill it with business logic and put it in a `shared` directory. 

Really enjoyed this exchange of ideas. Feel free to close it 😃

**Pull request closed without merging**
